function test_suite=test_assert_equal()
    initTestSuite;

function test_assert_equal_exceptions
    assertExceptionThrown(@()assertEqual(...
                                [1],'a'),...
                                        'moxunit:differentClass');
    assertExceptionThrown(@()assertEqual(...
                                [1 2],[1;2]),...
                                        'moxunit:differentSize');
    assertExceptionThrown(@()assertEqual(...
                                sparse(1),1),...
                                        'moxunit:differentSparsity');
    assertExceptionThrown(@()assertEqual(...
                                [1 2],[1 3]),...
                                        'moxunit:elementsNotEqual');

function test_assert_equal_passes
    assertEqual(1,1);
    assertEqual(struct(),struct());
    assertEqual({1,'a'},{1,'a'});

