function test_suite=test_assert_true()
    initTestSuite;

function test_assert_true_exceptions

    assertExceptionThrown(@()assertTrue(...
                                false),...
                                        'assertTrue:falseCondition');
    assertExceptionThrown(@()assertTrue(...
                                struct),...
                                        'assertTrue:invalidCondition');
    assertExceptionThrown(@()assertTrue(...
                                [true true]),...
                                        'assertTrue:invalidCondition');

function test_assert_true_passes
    assertTrue(true);

