function test_suite=test_assert_false()
    initTestSuite;

function test_assert_false_exceptions
    assertExceptionThrown(@()assertFalse(...
                                true),...
                                        'assertFalse:trueCondition');
    assertExceptionThrown(@()assertFalse(...
                                struct),...
                                        'assertFalse:invalidCondition');
    assertExceptionThrown(@()assertFalse(...
                                [false false]),...
                                        'assertFalse:invalidCondition');

function test_assert_false_passes
    assertFalse(false);
