function test_suite=test_assert_true()
    initTestSuite;

function test_assert_true_exceptions

    assertExceptionThrown(@()assertTrue(...
                                false),...
                                        'MOxUnit:notTrue');
    assertExceptionThrown(@()assertTrue(...
                                struct),...
                                        'MOxUnit:notLogicalScalar');
    assertExceptionThrown(@()assertTrue(...
                                [true true]),...
                                        'MOxUnit:notLogicalScalar');

function test_assert_true_passes
    assertTrue(true);

