function test_suite=test_assert_vectors_almost_equal()
    initTestSuite;

function test_assert_vectors_almost_equal_exceptions

    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                [],'a'),...
                                        'moxunit:notFloat');
    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                [1 2],[1;2]),...
                                        'moxunit:differentSize');
    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                sparse(1),1),...
                                        'moxunit:differentSparsity');
    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                [1 2],[1 3]),...
                                        'moxunit:floatsNotAlmostEqual');
    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                0,1e-10,'absolute',1e-11),...
                                        'moxunit:floatsNotAlmostEqual');
    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                0,1e-24,'relative',0,0),...
                                        'moxunit:floatsNotAlmostEqual');
    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                NaN,NaN),...
                                        'moxunit:floatsNotAlmostEqual');
    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                -Inf,-Inf),...
                                        'moxunit:floatsNotAlmostEqual');
    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                [1 2;3 4],1e-10+[1 2; 3 4]),...
                                        'moxunit:notVector');
    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                struct(),struct()),...
                                        'moxunit:notFloat');
    assertExceptionThrown(@()assertVectorsAlmostEqual(...
                                {1,'a'},{1,'a'}),...
                                        'moxunit:notFloat');





function test_assert_vectors_almost_equal_passes
    assertVectorsAlmostEqual(0,0);
    assertVectorsAlmostEqual(0,1e-10);
    assertVectorsAlmostEqual(0,1,'relative',1);
    assertVectorsAlmostEqual(0,1,'absolute',1);
    assertVectorsAlmostEqual(1:6,1e-10+(1:6))

