function test_suite=test_assert_greater_than()
    try % assignment of 'localfunctions' is necessary in Matlab >= 2016
        test_functions=localfunctions();
    catch % no problem; early Matlab versions can use initTestSuite fine
    end
    initTestSuite;

function test_assert_greater_than_exceptions
    assertExceptionThrown(@()assertGreaterThan(...
        [1],'a'),...
                          'assertGreaterThan:classNotEqual');
    assertExceptionThrown(@()assertGreaterThan(...
        [1 2],[1;2]),...
                          'assertGreaterThan:nonEqual');
    assertExceptionThrown(@()assertGreaterThan(...
        sparse(1),1),...
                          'assertGreaterThan:sparsityNotEqual');
    assertExceptionThrown(@()assertGreaterThan(...
        1,1),...
                          'assertGreaterThan:nonEqual');

function test_assert_greater_than_passes
    assertGreaterThan(2,1);
    assertGreaterThan([2,2],[1,1])
