---
name: CI octave action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:

# cancel previous runs on the same branch / PR
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

    unit-tests:

        runs-on: ubuntu-latest

        steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        -   uses: actions/checkout@v5

        # Use A Github Action to perform tests
        -   name: run unit tests and documentation tests, generate coverage report
            uses: joergbrech/moxunit-action@v1.1
            with:
                tests: tests
                src: MOxUnit
                with_coverage: true
                doc_tests: true
                cover_xml_file: coverage.xml

        -   name: Store Coverage report as artifact
            uses: actions/upload-artifact@v5
            with:
                name: coverage_xml_file
                path: coverage.xml
