---
name: validation

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

    validate_cff:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v5
        -   name: Check whether the citation metadata from CITATION.cff is valid
            uses: citation-file-format/cffconvert-github-action@2.0.0
            with:
                args: --validate
